include:
  - board: seeeduino_xiao_ble
    shield: zenith_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: seeeduino_xiao_ble
    shield: zenith_right    
    snippet: zmk-usb-logging 
  - board: seeeduino_xiao_ble
    shield: settings_reset
