include:
  - board: seeeduino_xiao_ble
    shield: zenith_left
    snippet: zmk-usb-logging 
  - board: seeeduino_xiao_ble
    shield: zenith_right    
    snippet: zmk-usb-logging 
  - board: seeeduino_xiao_ble
    shield: settings_reset
